-- HEY!
-- You're expected to already migrate models in GORM before running this script.

CREATE EXTENSION IF NOT EXISTS pg_trgm;

TRUNCATE TABLE roles RESTART IDENTITY CASCADE;
truncate table products restart identity cascade;
TRUNCATE TABLE categories RESTART IDENTITY CASCADE;
truncate table products_categories restart identity cascade;
truncate table users restart identity cascade;
truncate table bids restart identity cascade;
truncate table questions restart identity cascade;

CREATE INDEX IF NOT EXISTS idx_products_name_trgm ON products USING gin (name gin_trgm_ops);

-- Main User

INSERT INTO users (name, email, password, oauth_type, created_at, updated_at) VALUES ('Admin', 'admin@example.com', '$argon2id$v=19$m=65536,t=2,p=4$y7rT7dfnqb4NJOeqhVHEoA$UIaO/jNFwRH/Oz1qXcTOjzMpOSM+il1p835bbliZ6IM', 'none', now(), now());
INSERT INTO users (name, email, password, oauth_type, created_at, updated_at) VALUES ('Luna', 'luna@example.com', '$argon2id$v=19$m=65536,t=2,p=4$y7rT7dfnqb4NJOeqhVHEoA$UIaO/jNFwRH/Oz1qXcTOjzMpOSM+il1p835bbliZ6IM', 'none', now(), now());
INSERT INTO users (name, email, password, oauth_type, created_at, updated_at) VALUES ('MrGeraffe', 'mrgeraffe@example.com', '$argon2id$v=19$m=65536,t=2,p=4$y7rT7dfnqb4NJOeqhVHEoA$UIaO/jNFwRH/Oz1qXcTOjzMpOSM+il1p835bbliZ6IM', 'none', now(), now());
INSERT INTO users (name, email, password, oauth_type, created_at, updated_at) VALUES ('Omi', 'omi@example.com', '$argon2id$v=19$m=65536,t=2,p=4$y7rT7dfnqb4NJOeqhVHEoA$UIaO/jNFwRH/Oz1qXcTOjzMpOSM+il1p835bbliZ6IM', 'none', now(), now());

-- Roles.
-- Run this after you setup GORM to make sure you can register.

INSERT INTO roles (id, description, created_at, updated_at) VALUES
  ('user', 'Default role for all users', now(), now()),
  ('moderator', 'Moderation role', now(), now()),
  ('admin', 'Administrative role', now(), now());

INSERT INTO user_roles VALUES (1, 'user'), (1, 'moderator'), (1, 'admin');
INSERT INTO user_roles VALUES (2, 'user'), (2, 'moderator');
INSERT INTO user_roles VALUES (3, 'user');
INSERT INTO user_roles VALUES (4, 'user');

-- Seeding for categories.

insert into categories (name, created_at, updated_at) values ('Automotive', '2025-01-25 10:08:05', '2025-02-03 07:35:57');
insert into categories (name, created_at, updated_at) values ('Food - Baking', '2025-09-15 03:30:21', '2025-09-14 23:06:47');
insert into categories (name, created_at, updated_at) values ('Photography', '2025-12-19 20:40:14', '2025-06-14 07:11:25');
insert into categories (name, created_at, updated_at) values ('Beauty', '2025-10-11 18:22:09', '2025-02-17 00:34:14');
insert into categories (name, created_at, updated_at) values ('Pets', '2025-05-09 19:14:39', '2025-09-25 16:35:07');
insert into categories (name, created_at, updated_at) values ('Food - Snacks', '2025-11-21 09:01:03', '2025-09-21 07:24:13');
insert into categories (name, created_at, updated_at) values ('Outdoor', '2025-11-07 09:00:19', '2025-09-15 09:56:31');
insert into categories (name, created_at, updated_at) values ('Food - Canned Goods', '2025-04-20 21:28:32', '2025-05-03 20:10:01');
insert into categories (name, created_at, updated_at) values ('Garden', '2025-09-15 21:24:03', '2025-10-16 09:14:27');
insert into categories (name, created_at, updated_at) values ('Food - Spices', '2025-07-02 12:54:38', '2025-03-28 18:13:10');

insert into categories (name, parent_id, created_at, updated_at) values ('Nutritional Supplements', 8, '2025-08-19 01:14:04', '2025-08-06 23:29:45');
insert into categories (name, parent_id, created_at, updated_at) values ('Lighting', 8, '2025-05-03 15:11:27', '2025-01-22 23:12:00');
insert into categories (name, parent_id, created_at, updated_at) values ('Small Appliances', 9, '2025-02-07 00:31:20', '2025-11-23 04:37:16');
insert into categories (name, parent_id, created_at, updated_at) values ('Outdoor Accessories', 9, '2025-08-30 04:36:05', '2025-05-30 11:53:05');
insert into categories (name, parent_id, created_at, updated_at) values ('Gaming Accessories', 8, '2025-12-10 01:28:54', '2025-10-09 16:11:20');
insert into categories (name, parent_id, created_at, updated_at) values ('Educational Toys', 4, '2025-03-20 05:36:30', '2025-07-04 15:59:37');
insert into categories (name, parent_id, created_at, updated_at) values ('Pet Feeding Supplies', 6, '2025-05-28 13:45:16', '2025-07-20 00:57:19');
insert into categories (name, parent_id, created_at, updated_at) values ('Cooking Appliances', 5, '2025-06-13 02:54:33', '2025-07-25 06:42:57');
insert into categories (name, parent_id, created_at, updated_at) values ('Healthy Breakfast Options', 7, '2025-06-09 12:36:32', '2025-03-21 04:58:02');
insert into categories (name, parent_id, created_at, updated_at) values ('Marinated Poultry', 7, '2025-10-16 11:44:07', '2025-08-16 00:28:53');
insert into categories (name, parent_id, created_at, updated_at) values ('Spice Blends', 4, '2025-05-26 14:04:14', '2025-05-17 11:53:25');
insert into categories (name, parent_id, created_at, updated_at) values ('Decorative Wall Art & Accessories', 6, '2025-02-06 03:24:10', '2025-11-28 14:07:52');
insert into categories (name, parent_id, created_at, updated_at) values ('Regional Seasoning Blends', 3, '2025-01-07 13:56:11', '2025-12-02 09:26:33');
insert into categories (name, parent_id, created_at, updated_at) values ('Breads', 6, '2025-04-03 03:52:41', '2025-03-26 16:54:29');
insert into categories (name, parent_id, created_at, updated_at) values ('Small Appliances', 8, '2025-03-20 11:13:51', '2025-02-12 13:15:12');
insert into categories (name, parent_id, created_at, updated_at) values ('Portable Power Solutions', 9, '2025-10-03 10:31:37', '2025-12-13 18:10:35');
insert into categories (name, parent_id, created_at, updated_at) values ('Camping Equipment', 10, '2025-09-28 19:39:40', '2025-11-18 06:54:24');
insert into categories (name, parent_id, created_at, updated_at) values ('Furniture', 2, '2025-04-13 16:56:41', '2025-09-19 18:47:23');
insert into categories (name, parent_id, created_at, updated_at) values ('Massage Therapy', 6, '2025-10-01 03:34:47', '2025-10-05 23:10:56');
insert into categories (name, parent_id, created_at, updated_at) values ('Fresh Vegetables', 4, '2025-07-03 12:56:33', '2025-04-03 16:43:04');
insert into categories (name, parent_id, created_at, updated_at) values ('Baking Accessories', 8, '2025-01-22 22:44:47', '2025-10-24 13:17:25');
insert into categories (name, parent_id, created_at, updated_at) values ('Small Appliances', 10, '2025-01-06 10:17:40', '2025-08-30 14:08:06');
insert into categories (name, parent_id, created_at, updated_at) values ('Eco-Friendly Accessories', 9, '2025-03-04 13:42:57', '2025-11-29 05:50:37');
insert into categories (name, parent_id, created_at, updated_at) values ('Cereals', 10, '2025-04-07 07:12:44', '2025-06-24 13:16:24');
insert into categories (name, parent_id, created_at, updated_at) values ('Pickles', 8, '2025-01-04 09:50:20', '2025-09-04 22:48:35');
insert into categories (name, parent_id, created_at, updated_at) values ('Sweaters', 2, '2025-05-14 12:34:05', '2025-05-01 09:07:19');
insert into categories (name, parent_id, created_at, updated_at) values ('Granola and Muesli', 1, '2025-02-25 05:04:34', '2025-09-07 03:54:39');
insert into categories (name, parent_id, created_at, updated_at) values ('Air Quality & Purification', 1, '2025-01-30 14:07:16', '2025-01-13 03:01:08');
insert into categories (name, parent_id, created_at, updated_at) values ('Educational Toys', 9, '2025-06-22 14:12:59', '2025-07-17 02:26:04');
insert into categories (name, parent_id, created_at, updated_at) values ('Grain Salads', 8, '2025-10-29 15:07:37', '2025-03-10 19:58:41');

-- Seeding for products

insert into products (starting_bid, step_bid_type, step_bid_value, bin_price, allows_unrated_buyers, auto_extends_time, expired_at, seller_id, thumbnail_url, name, description, created_at, updated_at) values (29.99, 'percentage', 0.9214902736, 299.9, false, true, '2026-12-02 02:56:32', 2, 'http://dummyimage.com/154x233.png/dddddd/000000', 'Relaxed Fit Henley Shirt', 'A comfortable henley shirt made of soft cotton, perfect for casual outings.', now(), now());
insert into products (starting_bid, step_bid_type, step_bid_value, bin_price, allows_unrated_buyers, auto_extends_time, expired_at, seller_id, thumbnail_url, name, description, created_at, updated_at) values (8.99, 'fixed', 1.0973233493, 89.9, false, true, '2026-10-08 23:14:44', 1, 'http://dummyimage.com/202x226.png/ff4444/ffffff', 'Honey Sesame Chicken Mix', 'A meal kit featuring tender chicken with honey sesame sauce.', now(), now());
insert into products (starting_bid, step_bid_type, step_bid_value, bin_price, allows_unrated_buyers, auto_extends_time, expired_at, seller_id, thumbnail_url, name, description, created_at, updated_at) values (14.99, 'percentage', 0.5479855656, 149.9, true, false, '2026-04-26 02:50:39', 4, 'http://dummyimage.com/115x124.png/cc0000/ffffff', 'Pet Hair Removal Brush', 'Effective brush for removing loose hair from pets.', now(), now());
insert into products (starting_bid, step_bid_type, step_bid_value, bin_price, allows_unrated_buyers, auto_extends_time, expired_at, seller_id, thumbnail_url, name, description, created_at, updated_at) values (2.99, 'fixed', 0.3630703218, 29.9, false, true, '2026-06-22 23:35:02', 2, 'http://dummyimage.com/136x243.png/ff4444/ffffff', 'Spaghetti Sauce', 'Rich spaghetti sauce, a perfect pasta sauce.', now(), now());
insert into products (starting_bid, step_bid_type, step_bid_value, bin_price, allows_unrated_buyers, auto_extends_time, expired_at, seller_id, thumbnail_url, name, description, created_at, updated_at) values (11.99, 'percentage', 0.9473726894, 119.9, true, true, '2026-01-23 10:37:56', 4, 'http://dummyimage.com/187x198.png/5fa2dd/ffffff', 'Elderberry Syrup', 'Natural elderberry syrup to boost immunity.', now(), now());
insert into products (starting_bid, step_bid_type, step_bid_value, bin_price, allows_unrated_buyers, auto_extends_time, expired_at, seller_id, thumbnail_url, name, description, created_at, updated_at) values (5.49, 'percentage', 0.6733241297, 54.9, true, true, '2026-10-14 06:22:47', 4, 'http://dummyimage.com/149x225.png/cc0000/ffffff', 'Harvest Grain Salad', 'A hearty salad with grains, dried fruits, and nuts.', now(), now());
insert into products (starting_bid, step_bid_type, step_bid_value, bin_price, allows_unrated_buyers, auto_extends_time, expired_at, seller_id, thumbnail_url, name, description, created_at, updated_at) values (3.49, 'fixed', 0.4096985209, 34.9, false, false, '2026-04-27 12:32:36', 3, 'http://dummyimage.com/171x231.png/ff4444/ffffff', 'Apple Cinnamon Breakfast Muffins', 'Delicious muffins filled with apples and a hint of cinnamon for breakfast.', now(), now());
insert into products (starting_bid, step_bid_type, step_bid_value, bin_price, allows_unrated_buyers, auto_extends_time, expired_at, seller_id, thumbnail_url, name, description, created_at, updated_at) values (1.99, 'fixed', 0.3947001759, 19.9, false, false, '2026-03-07 11:07:33', 1, 'http://dummyimage.com/191x218.png/ff4444/ffffff', 'Frozen Spinach', 'Chopped and frozen spinach, ideal for cooking and smoothies.', now(), now());
insert into products (starting_bid, step_bid_type, step_bid_value, bin_price, allows_unrated_buyers, auto_extends_time, expired_at, seller_id, thumbnail_url, name, description, created_at, updated_at) values (12.99, 'fixed', 2.0610385291, 129.9, true, true, '2026-11-30 21:06:29', 4, 'http://dummyimage.com/134x160.png/5fa2dd/ffffff', 'Adjustable Skipping Rope', 'Durable skipping rope with adjustable length for workouts.', now(), now());
insert into products (starting_bid, step_bid_type, step_bid_value, bin_price, allows_unrated_buyers, auto_extends_time, expired_at, seller_id, thumbnail_url, name, description, created_at, updated_at) values (2.99, 'fixed', 0.5366455846, 29.9, true, true, '2026-07-12 11:42:08', 3, 'http://dummyimage.com/209x171.png/ff4444/ffffff', 'Savory Quinoa Pudding', 'A delicious savory quinoa pudding, great as a side dish.', now(), now());
insert into products (starting_bid, step_bid_type, step_bid_value, bin_price, allows_unrated_buyers, auto_extends_time, expired_at, seller_id, thumbnail_url, name, description, created_at, updated_at) values (2.89, 'fixed', 0.3708248285, 28.9, true, false, '2026-07-21 05:30:11', 2, 'http://dummyimage.com/150x223.png/5fa2dd/ffffff', 'Apple Cinnamon Oatmeal', 'Warm oatmeal flavored with apple and cinnamon.', now(), now());
insert into products (starting_bid, step_bid_type, step_bid_value, bin_price, allows_unrated_buyers, auto_extends_time, expired_at, seller_id, thumbnail_url, name, description, created_at, updated_at) values (1.99, 'percentage', 0.3599803937, 19.9, true, false, '2026-05-26 14:26:25', 2, 'http://dummyimage.com/110x212.png/cc0000/ffffff', 'Raspberry Limeade', 'Sweet and tangy raspberry lime beverage', now(), now());
insert into products (starting_bid, step_bid_type, step_bid_value, bin_price, allows_unrated_buyers, auto_extends_time, expired_at, seller_id, thumbnail_url, name, description, created_at, updated_at) values (1.99, 'fixed', 0.2672422332, 19.9, true, false, '2026-02-13 19:41:58', 2, 'http://dummyimage.com/206x103.png/cc0000/ffffff', 'Sliced Olives', 'Pitted black olives, perfect for salads and pizzas.', now(), now());
insert into products (starting_bid, step_bid_type, step_bid_value, bin_price, allows_unrated_buyers, auto_extends_time, expired_at, seller_id, thumbnail_url, name, description, created_at, updated_at) values (5.49, 'fixed', 1.0141614986, 54.9, false, true, '2026-06-16 02:10:03', 1, 'http://dummyimage.com/239x168.png/dddddd/000000', 'Sliced Ham', 'Delicious and fully cooked sliced ham, ready to eat.', now(), now());
insert into products (starting_bid, step_bid_type, step_bid_value, bin_price, allows_unrated_buyers, auto_extends_time, expired_at, seller_id, thumbnail_url, name, description, created_at, updated_at) values (8.99, 'fixed', 1.4133207006, 89.9, false, true, '2026-04-23 07:32:28', 2, 'http://dummyimage.com/174x175.png/dddddd/000000', 'Organic Almonds', 'Crunchy and nutritious almonds, perfect for snacking.', now(), now());
insert into products (starting_bid, step_bid_type, step_bid_value, bin_price, allows_unrated_buyers, auto_extends_time, expired_at, seller_id, thumbnail_url, name, description, created_at, updated_at) values (18.99, 'fixed', 2.8578051452, 189.9, false, false, '2026-02-02 00:17:19', 4, 'http://dummyimage.com/218x133.png/ff4444/ffffff', 'Water Bottle', 'Insulated water bottle for keeping drinks cold.', now(), now());
insert into products (starting_bid, step_bid_type, step_bid_value, bin_price, allows_unrated_buyers, auto_extends_time, expired_at, seller_id, thumbnail_url, name, description, created_at, updated_at) values (18.99, 'percentage', 0.8292566872, 189.9, true, false, '2026-01-06 10:15:15', 2, 'http://dummyimage.com/103x113.png/cc0000/ffffff', 'Hand Crank Blender', 'Manual blender for smoothies and mixing ingredients on the go.', now(), now());
insert into products (starting_bid, step_bid_type, step_bid_value, bin_price, allows_unrated_buyers, auto_extends_time, expired_at, seller_id, thumbnail_url, name, description, created_at, updated_at) values (3.29, 'percentage', 0.4281595702, 32.9, false, false, '2026-04-09 12:33:22', 4, 'http://dummyimage.com/210x127.png/ff4444/ffffff', 'Spicy Thai Chili Sauce', 'A sweet and spicy sauce for dipping or cooking.', now(), now());
insert into products (starting_bid, step_bid_type, step_bid_value, bin_price, allows_unrated_buyers, auto_extends_time, expired_at, seller_id, thumbnail_url, name, description, created_at, updated_at) values (34.99, 'fixed', 5.5606744353, 349.9, true, false, '2026-05-03 18:51:38', 4, 'http://dummyimage.com/241x110.png/ff4444/ffffff', 'Bamboo Memory Foam Pillow', 'Ergonomically designed pillow with breathable bamboo cover.', now(), now());
insert into products (starting_bid, step_bid_type, step_bid_value, bin_price, allows_unrated_buyers, auto_extends_time, expired_at, seller_id, thumbnail_url, name, description, created_at, updated_at) values (14.99, 'fixed', 2.9044332426, 149.9, false, false, '2026-06-22 01:30:40', 4, 'http://dummyimage.com/190x209.png/5fa2dd/ffffff', 'Home Delivery Food Journal', 'Track your meals and nutrition with this handy food journal.', now(), now());
insert into products (starting_bid, step_bid_type, step_bid_value, bin_price, allows_unrated_buyers, auto_extends_time, expired_at, seller_id, thumbnail_url, name, description, created_at, updated_at) values (69.99, 'fixed', 13.7954684959, 699.9, true, true, '2026-08-22 07:29:40', 4, 'http://dummyimage.com/145x104.png/5fa2dd/ffffff', 'Portable Speakers', 'Bluetooth speakers with excellent sound quality.', now(), now());
insert into products (starting_bid, step_bid_type, step_bid_value, bin_price, allows_unrated_buyers, auto_extends_time, expired_at, seller_id, thumbnail_url, name, description, created_at, updated_at) values (4.99, 'percentage', 0.9040923855, 49.9, true, true, '2026-03-04 21:40:26', 2, 'http://dummyimage.com/120x229.png/dddddd/000000', 'Roasted Garlic Pasta Sauce', 'A flavorful pasta sauce made with roasted garlic.', now(), now());
insert into products (starting_bid, step_bid_type, step_bid_value, bin_price, allows_unrated_buyers, auto_extends_time, expired_at, seller_id, thumbnail_url, name, description, created_at, updated_at) values (1.29, 'percentage', 0.1165325158, 12.9, false, false, '2026-12-31 01:10:58', 4, 'http://dummyimage.com/226x115.png/ff4444/ffffff', 'Ramen Noodle Soup Cups', 'Instant ramen cups with flavor-packed broth.', now(), now());
insert into products (starting_bid, step_bid_type, step_bid_value, bin_price, allows_unrated_buyers, auto_extends_time, expired_at, seller_id, thumbnail_url, name, description, created_at, updated_at) values (3.79, 'percentage', 0.4205322831, 37.9, false, false, '2026-11-04 17:21:28', 2, 'http://dummyimage.com/176x246.png/cc0000/ffffff', 'Chocolate Coconut Granola', 'Crunchy granola with chocolate and coconut, great for breakfast or snacks.', now(), now());
insert into products (starting_bid, step_bid_type, step_bid_value, bin_price, allows_unrated_buyers, auto_extends_time, expired_at, seller_id, thumbnail_url, name, description, created_at, updated_at) values (19.99, 'percentage', 0.6962227269, 199.9, false, false, '2026-12-14 06:48:27', 1, 'http://dummyimage.com/227x192.png/cc0000/ffffff', 'Rustic Wooden Picture Frame', 'Charming frame to showcase your favorite photos.', now(), now());
insert into products (starting_bid, step_bid_type, step_bid_value, bin_price, allows_unrated_buyers, auto_extends_time, expired_at, seller_id, thumbnail_url, name, description, created_at, updated_at) values (5.99, 'percentage', 0.1927973809, 59.9, false, false, '2026-09-21 06:20:20', 3, 'http://dummyimage.com/138x209.png/ff4444/ffffff', 'Organic Granola Cereal', 'Crunchy granola made with organic oats', now(), now());
insert into products (starting_bid, step_bid_type, step_bid_value, bin_price, allows_unrated_buyers, auto_extends_time, expired_at, seller_id, thumbnail_url, name, description, created_at, updated_at) values (49.99, 'percentage', 0.9983201128, 499.9, false, true, '2026-04-04 01:12:52', 1, 'http://dummyimage.com/206x188.png/5fa2dd/ffffff', 'Classic Slim Fit Shirt', 'A tailored slim fit shirt for a polished look at work.', now(), now());
insert into products (starting_bid, step_bid_type, step_bid_value, bin_price, allows_unrated_buyers, auto_extends_time, expired_at, seller_id, thumbnail_url, name, description, created_at, updated_at) values (59.99, 'fixed', 8.5790225659, 599.9, true, false, '2026-03-29 16:38:35', 2, 'http://dummyimage.com/169x113.png/dddddd/000000', 'Pet Activity Tracker', 'GPS collar that monitors your pet''s location and activity level.', now(), now());
insert into products (starting_bid, step_bid_type, step_bid_value, bin_price, allows_unrated_buyers, auto_extends_time, expired_at, seller_id, thumbnail_url, name, description, created_at, updated_at) values (16.99, 'percentage', 0.9789296631, 169.9, false, true, '2026-05-29 22:55:40', 4, 'http://dummyimage.com/127x233.png/5fa2dd/ffffff', 'Pet Grooming Scissors', 'Quality scissors designed for easy pet grooming.', now(), now());
insert into products (starting_bid, step_bid_type, step_bid_value, bin_price, allows_unrated_buyers, auto_extends_time, expired_at, seller_id, thumbnail_url, name, description, created_at, updated_at) values (3.99, 'percentage', 0.385494549, 39.9, false, true, '2026-08-31 12:40:27', 1, 'http://dummyimage.com/217x110.png/dddddd/000000', 'Thai Coconut Curry Sauce', 'A rich coconut curry sauce perfect for simmering vegetables or meats.', now(), now());
insert into products (starting_bid, step_bid_type, step_bid_value, bin_price, allows_unrated_buyers, auto_extends_time, expired_at, seller_id, thumbnail_url, name, description, created_at, updated_at) values (2.49, 'percentage', 0.4530392927, 24.9, true, true, '2026-11-03 09:08:02', 3, 'http://dummyimage.com/149x138.png/dddddd/000000', 'Vegetarian Stir Fry Sauce', 'Flavorful sauce perfect for stir-frying vegetables and tofu.', now(), now());
insert into products (starting_bid, step_bid_type, step_bid_value, bin_price, allows_unrated_buyers, auto_extends_time, expired_at, seller_id, thumbnail_url, name, description, created_at, updated_at) values (34.99, 'percentage', 0.5865871626, 349.9, false, false, '2026-02-22 21:06:20', 1, 'http://dummyimage.com/110x109.png/dddddd/000000', 'Garden Hoses with Expandable Features', 'Lightweight, expandable hoses for easy handling.', now(), now());
insert into products (starting_bid, step_bid_type, step_bid_value, bin_price, allows_unrated_buyers, auto_extends_time, expired_at, seller_id, thumbnail_url, name, description, created_at, updated_at) values (6.49, 'percentage', 0.5219410612, 64.9, true, true, '2026-07-12 09:32:31', 4, 'http://dummyimage.com/115x196.png/5fa2dd/ffffff', 'Kale and Quinoa Salad', 'A nutritious salad with kale, quinoa, and a zesty lemon dressing.', now(), now());
insert into products (starting_bid, step_bid_type, step_bid_value, bin_price, allows_unrated_buyers, auto_extends_time, expired_at, seller_id, thumbnail_url, name, description, created_at, updated_at) values (29.99, 'percentage', 0.2659551515, 299.9, false, false, '2026-06-06 00:11:54', 2, 'http://dummyimage.com/223x115.png/cc0000/ffffff', 'Fitness Tracker Band', 'Affordable fitness tracker with heart rate monitor.', now(), now());
insert into products (starting_bid, step_bid_type, step_bid_value, bin_price, allows_unrated_buyers, auto_extends_time, expired_at, seller_id, thumbnail_url, name, description, created_at, updated_at) values (29.99, 'fixed', 5.7531469319, 299.9, true, true, '2026-09-05 06:31:01', 4, 'http://dummyimage.com/168x209.png/dddddd/000000', 'Mini Hand Gesture Drone', 'Toy drone that flies with gestures and is easy to control.', now(), now());
insert into products (starting_bid, step_bid_type, step_bid_value, bin_price, allows_unrated_buyers, auto_extends_time, expired_at, seller_id, thumbnail_url, name, description, created_at, updated_at) values (25, 'fixed', 3.3246596602, 250, true, false, '2026-05-24 03:37:44', 3, 'http://dummyimage.com/243x208.png/cc0000/ffffff', 'Nail Polish Set', 'Assorted nail polish set for vibrant nails.', now(), now());
insert into products (starting_bid, step_bid_type, step_bid_value, bin_price, allows_unrated_buyers, auto_extends_time, expired_at, seller_id, thumbnail_url, name, description, created_at, updated_at) values (3.29, 'percentage', 0.1656063002, 32.9, true, true, '2026-09-02 03:50:59', 1, 'http://dummyimage.com/219x136.png/dddddd/000000', 'Pumpkin Spice Latte Mix', 'Instant mix for delicious pumpkin spice lattes at home.', now(), now());
insert into products (starting_bid, step_bid_type, step_bid_value, bin_price, allows_unrated_buyers, auto_extends_time, expired_at, seller_id, thumbnail_url, name, description, created_at, updated_at) values (2.79, 'fixed', 0.3000069053, 27.9, false, false, '2026-12-22 17:28:09', 2, 'http://dummyimage.com/102x205.png/cc0000/ffffff', 'Garam Masala Spice Blend', 'A fragrant Indian spice blend for curries and stews.', now(), now());
insert into products (starting_bid, step_bid_type, step_bid_value, bin_price, allows_unrated_buyers, auto_extends_time, expired_at, seller_id, thumbnail_url, name, description, created_at, updated_at) values (1.99, 'percentage', 0.8942899426, 19.9, false, true, '2026-09-08 10:20:16', 1, 'http://dummyimage.com/181x150.png/cc0000/ffffff', 'Cajun Seasoning', 'Spicy seasoning mix for all your favorite dishes.', now(), now());
insert into products (starting_bid, step_bid_type, step_bid_value, bin_price, allows_unrated_buyers, auto_extends_time, expired_at, seller_id, thumbnail_url, name, description, created_at, updated_at) values (4.29, 'percentage', 0.9910853645, 42.9, false, true, '2026-02-21 21:24:38', 4, 'http://dummyimage.com/111x127.png/dddddd/000000', 'Cranberry Almond Granola', 'Crunchy granola with oats, almonds, and dried cranberries.', now(), now());
insert into products (starting_bid, step_bid_type, step_bid_value, bin_price, allows_unrated_buyers, auto_extends_time, expired_at, seller_id, thumbnail_url, name, description, created_at, updated_at) values (2.49, 'fixed', 0.3846216791, 24.9, false, false, '2026-03-16 05:01:33', 4, 'http://dummyimage.com/229x182.png/ff4444/ffffff', 'Organic Brown Sugar', 'Natural sweetener for baking and cooking.', now(), now());
insert into products (starting_bid, step_bid_type, step_bid_value, bin_price, allows_unrated_buyers, auto_extends_time, expired_at, seller_id, thumbnail_url, name, description, created_at, updated_at) values (1.99, 'fixed', 0.3934277754, 19.9, false, true, '2026-03-04 11:23:32', 4, 'http://dummyimage.com/201x174.png/ff4444/ffffff', 'Spicy Beef Taco Mix', 'Easy mix for making spicy beef tacos.', now(), now());
insert into products (starting_bid, step_bid_type, step_bid_value, bin_price, allows_unrated_buyers, auto_extends_time, expired_at, seller_id, thumbnail_url, name, description, created_at, updated_at) values (34.99, 'fixed', 4.744476604, 349.9, true, false, '2026-02-24 06:37:34', 1, 'http://dummyimage.com/154x233.png/ff4444/ffffff', 'Handheld Shower Head', 'Adjustable shower head for a luxurious shower experience.', now(), now());
insert into products (starting_bid, step_bid_type, step_bid_value, bin_price, allows_unrated_buyers, auto_extends_time, expired_at, seller_id, thumbnail_url, name, description, created_at, updated_at) values (5.99, 'fixed', 0.6357672705, 59.9, true, true, '2026-04-20 08:21:50', 1, 'http://dummyimage.com/119x183.png/5fa2dd/ffffff', 'Kale Caesar Salad Kit', 'Fresh kale with Caesar dressing and croutons.', now(), now());
insert into products (starting_bid, step_bid_type, step_bid_value, bin_price, allows_unrated_buyers, auto_extends_time, expired_at, seller_id, thumbnail_url, name, description, created_at, updated_at) values (19.99, 'fixed', 3.0892323239, 199.9, true, true, '2026-06-02 08:35:31', 1, 'http://dummyimage.com/178x178.png/dddddd/000000', 'Snack Container Set', 'Stackable containers for organizing snacks and treats.', now(), now());
insert into products (starting_bid, step_bid_type, step_bid_value, bin_price, allows_unrated_buyers, auto_extends_time, expired_at, seller_id, thumbnail_url, name, description, created_at, updated_at) values (5.99, 'percentage', 0.837092167, 59.9, true, true, '2026-08-05 16:31:37', 3, 'http://dummyimage.com/227x105.png/ff4444/ffffff', 'Veggie Burger Patties', 'Delicious veggie burger patties for grilling or frying.', now(), now());
insert into products (starting_bid, step_bid_type, step_bid_value, bin_price, allows_unrated_buyers, auto_extends_time, expired_at, seller_id, thumbnail_url, name, description, created_at, updated_at) values (4.99, 'fixed', 0.6553895661, 49.9, true, true, '2026-07-01 08:32:45', 4, 'http://dummyimage.com/246x113.png/ff4444/ffffff', 'Berry Smoothie Mix', 'Frozen mix for quick berry smoothies.', now(), now());
insert into products (starting_bid, step_bid_type, step_bid_value, bin_price, allows_unrated_buyers, auto_extends_time, expired_at, seller_id, thumbnail_url, name, description, created_at, updated_at) values (3.99, 'percentage', 0.8973453577, 39.9, false, false, '2026-05-12 13:58:32', 4, 'http://dummyimage.com/113x113.png/5fa2dd/ffffff', 'Spicy Thai Coconut Soup', 'A ready-to-eat soup with coconut milk, spices, and vegetables.', now(), now());
insert into products (starting_bid, step_bid_type, step_bid_value, bin_price, allows_unrated_buyers, auto_extends_time, expired_at, seller_id, thumbnail_url, name, description, created_at, updated_at) values (29.99, 'fixed', 4.9532065213, 299.9, true, false, '2026-02-11 07:59:34', 2, 'http://dummyimage.com/202x179.png/ff4444/ffffff', 'Stainless Steel Cutlery Set', 'High-quality cutlery set for daily use or special occasions.', now(), now());
insert into products (starting_bid, step_bid_type, step_bid_value, bin_price, allows_unrated_buyers, auto_extends_time, expired_at, seller_id, thumbnail_url, name, description, created_at, updated_at) values (4.99, 'percentage', 0.399488328, 49.9, false, true, '2026-11-19 17:31:27', 2, 'http://dummyimage.com/177x234.png/ff4444/ffffff', 'Crispy Tofu Bites', 'Crispy on the outside, tender on the inside, perfect for stir-fries or salads.', now(), now());
insert into products (starting_bid, step_bid_type, step_bid_value, bin_price, allows_unrated_buyers, auto_extends_time, expired_at, seller_id, thumbnail_url, name, description, created_at, updated_at) values (4.99, 'percentage', 0.399488328, 49.9, false, true, '2026-11-19 17:31:27', 2, 'http://dummyimage.com/177x234.png/ff4444/ffffff', 'Crispy Tofu Bites', 'Crispy on the outside, tender on the inside, perfect for stir-fries or salads.', now(), now());
insert into products (starting_bid, step_bid_type, step_bid_value, bin_price, allows_unrated_buyers, auto_extends_time, expired_at, seller_id, thumbnail_url, name, description) values (69.0, 'percentage', 0.47, 420.0, true, true, '2/17/2027', 2, 'https://cdn.luny.dev/online-news/676e8efdf6aa2cb546216767-large.webp', 'さくらちゃん', '桜ちゃんかわいいですね。主無きものよ、夢の杖のもと、われの力になれ。');
insert into products (starting_bid, step_bid_type, step_bid_value, bin_price, allows_unrated_buyers, auto_extends_time, expired_at, seller_id, thumbnail_url, name, description) values (69.0, 'percentage', 0.47, 420.0, true, true, '2026-01-01 00:00:00', 2, 'https://cdn.luny.dev/online-news/676e8efdf6aa2cb546216767-large.webp', 'Test Product 1', 'Test Description');

-- Update TS Vector.
update products set search_vector = to_tsvector('simple', name || ' ' || description);

-- Seeding for products/categories

insert into products_categories (product_id, category_id) values (1, 34);
insert into products_categories (product_id, category_id) values (2, 28);
insert into products_categories (product_id, category_id) values (3, 16);
insert into products_categories (product_id, category_id) values (4, 31);
insert into products_categories (product_id, category_id) values (5, 17);
insert into products_categories (product_id, category_id) values (6, 7);
insert into products_categories (product_id, category_id) values (7, 13);
insert into products_categories (product_id, category_id) values (8, 6);
insert into products_categories (product_id, category_id) values (9, 10);
insert into products_categories (product_id, category_id) values (10, 11);
insert into products_categories (product_id, category_id) values (11, 30);
insert into products_categories (product_id, category_id) values (12, 12);
insert into products_categories (product_id, category_id) values (13, 4);
insert into products_categories (product_id, category_id) values (14, 28);
insert into products_categories (product_id, category_id) values (15, 11);
insert into products_categories (product_id, category_id) values (16, 2);
insert into products_categories (product_id, category_id) values (17, 27);
insert into products_categories (product_id, category_id) values (18, 17);
insert into products_categories (product_id, category_id) values (19, 13);
insert into products_categories (product_id, category_id) values (20, 27);
insert into products_categories (product_id, category_id) values (21, 29);
insert into products_categories (product_id, category_id) values (22, 5);
insert into products_categories (product_id, category_id) values (23, 3);
insert into products_categories (product_id, category_id) values (24, 15);
insert into products_categories (product_id, category_id) values (25, 33);
insert into products_categories (product_id, category_id) values (26, 19);
insert into products_categories (product_id, category_id) values (27, 13);
insert into products_categories (product_id, category_id) values (28, 6);
insert into products_categories (product_id, category_id) values (29, 6);
insert into products_categories (product_id, category_id) values (30, 27);
insert into products_categories (product_id, category_id) values (31, 38);
insert into products_categories (product_id, category_id) values (32, 1);
insert into products_categories (product_id, category_id) values (33, 14);
insert into products_categories (product_id, category_id) values (34, 23);
insert into products_categories (product_id, category_id) values (35, 26);
insert into products_categories (product_id, category_id) values (36, 33);
insert into products_categories (product_id, category_id) values (37, 38);
insert into products_categories (product_id, category_id) values (38, 4);
insert into products_categories (product_id, category_id) values (39, 9);
insert into products_categories (product_id, category_id) values (40, 15);
insert into products_categories (product_id, category_id) values (41, 11);
insert into products_categories (product_id, category_id) values (42, 7);
insert into products_categories (product_id, category_id) values (43, 7);
insert into products_categories (product_id, category_id) values (44, 40);
insert into products_categories (product_id, category_id) values (45, 11);
insert into products_categories (product_id, category_id) values (46, 4);
insert into products_categories (product_id, category_id) values (47, 25);
insert into products_categories (product_id, category_id) values (48, 3);
insert into products_categories (product_id, category_id) values (49, 33);
insert into products_categories (product_id, category_id) values (50, 24);

-- Seeding product images

insert into product_images (product_id, url, alt_text) values (1, 'http://dummyimage.com/163x242.png/cc0000/ffffff', 'Everything you need to make your own scented candles at home.');
insert into product_images (product_id, url, alt_text) values (2, 'http://dummyimage.com/223x190.png/cc0000/ffffff', 'Natural energy bites packed with fruits and nuts for a perfect snack.');
insert into product_images (product_id, url, alt_text) values (3, 'http://dummyimage.com/194x226.png/dddddd/000000', 'Multi-function pressure cooker that can sauté, steam, and slow cook.');
insert into product_images (product_id, url, alt_text) values (4, 'http://dummyimage.com/183x233.png/cc0000/ffffff', 'Gentle glove for brushing and massaging your pet.');
insert into product_images (product_id, url, alt_text) values (5, 'http://dummyimage.com/197x217.png/cc0000/ffffff', 'Savory pizza filled with pepperoni and cheese, ready to microwave.');
insert into product_images (product_id, url, alt_text) values (6, 'http://dummyimage.com/248x222.png/dddddd/000000', 'Stylish bar stools with adjustable height and swivel features.');
insert into product_images (product_id, url, alt_text) values (7, 'http://dummyimage.com/195x188.png/cc0000/ffffff', 'All-in-one meal kit including pasta, meatballs, and sauce for a quick dinner.');
insert into product_images (product_id, url, alt_text) values (8, 'http://dummyimage.com/117x183.png/cc0000/ffffff', 'Ergonomic monitor stand for improved workspace organization.');
insert into product_images (product_id, url, alt_text) values (9, 'http://dummyimage.com/161x101.png/ff4444/ffffff', 'Wi-Fi-enabled digital frame for displaying photos.');
insert into product_images (product_id, url, alt_text) values (10, 'http://dummyimage.com/159x131.png/5fa2dd/ffffff', 'Adjustable grinders for fresh spices at the table.');
insert into product_images (product_id, url, alt_text) values (11, 'http://dummyimage.com/149x117.png/cc0000/ffffff', 'Control lights remotely with this smart switch.');
insert into product_images (product_id, url, alt_text) values (12, 'http://dummyimage.com/225x232.png/ff4444/ffffff', 'Durable gardening gloves with reinforced fingertips.');
insert into product_images (product_id, url, alt_text) values (13, 'http://dummyimage.com/132x224.png/dddddd/000000', 'Compact action camera for capturing adventures.');
insert into product_images (product_id, url, alt_text) values (14, 'http://dummyimage.com/174x135.png/ff4444/ffffff', 'Beginner telescope for stargazing and exploring.');
insert into product_images (product_id, url, alt_text) values (15, 'http://dummyimage.com/237x141.png/5fa2dd/ffffff', 'Creamy and delicious soup made with real butternut squash, ready to heat.');
insert into product_images (product_id, url, alt_text) values (16, 'http://dummyimage.com/220x186.png/dddddd/000000', 'Cook rice and steam vegetables simultaneously for healthy meals.');
insert into product_images (product_id, url, alt_text) values (17, 'http://dummyimage.com/166x192.png/5fa2dd/ffffff', 'Everything you need for a fresh and delicious Caesar salad.');
insert into product_images (product_id, url, alt_text) values (18, 'http://dummyimage.com/135x250.png/cc0000/ffffff', 'Thermos that tracks your water intake and temperature.');
insert into product_images (product_id, url, alt_text) values (19, 'http://dummyimage.com/220x246.png/cc0000/ffffff', 'Stainless steel measuring spoons set for cooking.');
insert into product_images (product_id, url, alt_text) values (20, 'http://dummyimage.com/111x169.png/5fa2dd/ffffff', 'High-intensity flashlight with adjustable focus and brightness.');
insert into product_images (product_id, url, alt_text) values (21, 'http://dummyimage.com/114x209.png/dddddd/000000', 'Comfortable gaming headset with surround sound.');
insert into product_images (product_id, url, alt_text) values (22, 'http://dummyimage.com/245x180.png/ff4444/ffffff', 'Extra virgin olive oil infused with fresh basil.');
insert into product_images (product_id, url, alt_text) values (23, 'http://dummyimage.com/151x164.png/ff4444/ffffff', 'Fresh thyme, perfect for seasoning dishes.');
insert into product_images (product_id, url, alt_text) values (24, 'http://dummyimage.com/232x241.png/ff4444/ffffff', 'Organic rolled oats, great for breakfast or baking.');
insert into product_images (product_id, url, alt_text) values (25, 'http://dummyimage.com/138x214.png/5fa2dd/ffffff', 'Convert your desk to a standing desk easily.');
insert into product_images (product_id, url, alt_text) values (26, 'http://dummyimage.com/238x115.png/ff4444/ffffff', 'Practical organizer for keeping your home tidy and clutter-free.');
insert into product_images (product_id, url, alt_text) values (27, 'http://dummyimage.com/128x246.png/ff4444/ffffff', 'Foldable kneeler that doubles as a seat for gardening convenience.');
insert into product_images (product_id, url, alt_text) values (28, 'http://dummyimage.com/132x214.png/5fa2dd/ffffff', 'A refreshing blend of peaches and mangoes for a delicious smoothie.');
insert into product_images (product_id, url, alt_text) values (29, 'http://dummyimage.com/118x150.png/ff4444/ffffff', 'Digital scale for precise cooking measurements.');
insert into product_images (product_id, url, alt_text) values (30, 'http://dummyimage.com/155x159.png/5fa2dd/ffffff', 'Dairy-free cheese alternative for your favorite dishes.');
insert into product_images (product_id, url, alt_text) values (31, 'http://dummyimage.com/154x166.png/cc0000/ffffff', 'Spicy chili sauce with garlic and sugar for a flavor kick.');
insert into product_images (product_id, url, alt_text) values (32, 'http://dummyimage.com/112x120.png/cc0000/ffffff', 'Protective gaiters to keep dirt and debris out of shoes during hikes.');
insert into product_images (product_id, url, alt_text) values (33, 'http://dummyimage.com/230x195.png/5fa2dd/ffffff', 'Eco-friendly soy candles with a variety of scents.');
insert into product_images (product_id, url, alt_text) values (34, 'http://dummyimage.com/193x244.png/dddddd/000000', 'Assorted sliced cheese, perfect for sandwiches.');
insert into product_images (product_id, url, alt_text) values (35, 'http://dummyimage.com/247x244.png/dddddd/000000', 'Solar-powered charger for smartphones and tablets.');
insert into product_images (product_id, url, alt_text) values (36, 'http://dummyimage.com/160x111.png/ff4444/ffffff', 'Personalized calendar with your favorite photos.');
insert into product_images (product_id, url, alt_text) values (37, 'http://dummyimage.com/230x113.png/cc0000/ffffff', 'Skillet that can fry, grill, and sauté with ease.');
insert into product_images (product_id, url, alt_text) values (38, 'http://dummyimage.com/160x107.png/5fa2dd/ffffff', 'Easy mix for making spicy beef tacos.');
insert into product_images (product_id, url, alt_text) values (39, 'http://dummyimage.com/139x230.png/ff4444/ffffff', 'Elegant midi skirt with a wrap design, great for both formal and casual events.');
insert into product_images (product_id, url, alt_text) values (40, 'http://dummyimage.com/155x236.png/5fa2dd/ffffff', 'Prevent water damage with drip trays for potted plants.');
insert into product_images (product_id, url, alt_text) values (41, 'http://dummyimage.com/137x107.png/5fa2dd/ffffff', 'Frozen mini meatballs that are great as a snack or in pasta dishes.');
insert into product_images (product_id, url, alt_text) values (42, 'http://dummyimage.com/159x189.png/5fa2dd/ffffff', 'Instant noodles with a spicy Thai sauce for quick meals.');
insert into product_images (product_id, url, alt_text) values (43, 'http://dummyimage.com/160x169.png/5fa2dd/ffffff', 'Handy keychain that emits a loud alarm for personal safety.');
insert into product_images (product_id, url, alt_text) values (44, 'http://dummyimage.com/186x108.png/ff4444/ffffff', 'Thin, flat pasta perfect for various sauces.');
insert into product_images (product_id, url, alt_text) values (45, 'http://dummyimage.com/193x156.png/ff4444/ffffff', 'Color-changing 3D night light for kids'' rooms.');
insert into product_images (product_id, url, alt_text) values (46, 'http://dummyimage.com/227x239.png/cc0000/ffffff', 'Marinated chicken grilled with lemon and herbs.');
insert into product_images (product_id, url, alt_text) values (47, 'http://dummyimage.com/203x181.png/5fa2dd/ffffff', 'Tender chicken coated in a sweet and savory honey garlic sauce.');
insert into product_images (product_id, url, alt_text) values (48, 'http://dummyimage.com/205x161.png/5fa2dd/ffffff', 'High-frequency whistle for training your dog effectively.');
insert into product_images (product_id, url, alt_text) values (49, 'http://dummyimage.com/230x173.png/5fa2dd/ffffff', 'Advanced electric toothbrush for effective cleaning.');
insert into product_images (product_id, url, alt_text) values (50, 'http://dummyimage.com/116x236.png/ff4444/ffffff', 'Delicious veggie burger patties for grilling or frying.');
insert into product_images (product_id, url, alt_text) values (1, 'http://dummyimage.com/105x231.png/ff4444/ffffff', 'Unique coffee brewing method for a flavorful experience.');
insert into product_images (product_id, url, alt_text) values (2, 'http://dummyimage.com/202x118.png/ff4444/ffffff', 'Delicious waffles infused with pumpkin and spices.');
insert into product_images (product_id, url, alt_text) values (3, 'http://dummyimage.com/187x245.png/dddddd/000000', 'Refreshing dessert bars made with pineapple and coconut.');
insert into product_images (product_id, url, alt_text) values (4, 'http://dummyimage.com/228x208.png/cc0000/ffffff', 'Crispy and crunchy snack made from assorted vegetables.');
insert into product_images (product_id, url, alt_text) values (5, 'http://dummyimage.com/130x231.png/5fa2dd/ffffff', 'Lightweight backpack with an insulated water reservoir for hydration on the go.');
insert into product_images (product_id, url, alt_text) values (6, 'http://dummyimage.com/221x173.png/dddddd/000000', 'Classic wooden puzzle game for kids and adults.');
insert into product_images (product_id, url, alt_text) values (7, 'http://dummyimage.com/233x146.png/dddddd/000000', 'A delicious tart filled with fresh raspberry filling.');
insert into product_images (product_id, url, alt_text) values (8, 'http://dummyimage.com/170x115.png/cc0000/ffffff', 'Hard-shell case for protecting sunglasses.');
insert into product_images (product_id, url, alt_text) values (9, 'http://dummyimage.com/223x230.png/5fa2dd/ffffff', 'Stylish faux leather leggings for a trendy outfit.');
insert into product_images (product_id, url, alt_text) values (10, 'http://dummyimage.com/121x111.png/ff4444/ffffff', 'Personal massager for muscle recovery.');
insert into product_images (product_id, url, alt_text) values (11, 'http://dummyimage.com/133x245.png/dddddd/000000', 'Thermos that tracks your water intake and temperature.');
insert into product_images (product_id, url, alt_text) values (12, 'http://dummyimage.com/110x189.png/ff4444/ffffff', 'Customizable RGB LED light strip, perfect for mood lighting.');
insert into product_images (product_id, url, alt_text) values (13, 'http://dummyimage.com/178x212.png/dddddd/000000', 'Adjustable window blinds for privacy and light control.');
insert into product_images (product_id, url, alt_text) values (14, 'http://dummyimage.com/197x184.png/5fa2dd/ffffff', 'Sweet and crunchy honey-flavored graham crackers.');
insert into product_images (product_id, url, alt_text) values (15, 'http://dummyimage.com/133x223.png/dddddd/000000', 'Thick and durable mat for workouts and yoga.');
insert into product_images (product_id, url, alt_text) values (16, 'http://dummyimage.com/185x177.png/dddddd/000000', 'Double-walled mug to keep your drink hot for longer.');
insert into product_images (product_id, url, alt_text) values (17, 'http://dummyimage.com/120x222.png/dddddd/000000', 'Durable canvas tote bag, perfect for everyday use.');
insert into product_images (product_id, url, alt_text) values (18, 'http://dummyimage.com/247x205.png/5fa2dd/ffffff', 'Frozen vegetable primavera for quick meals.');
insert into product_images (product_id, url, alt_text) values (19, 'http://dummyimage.com/172x152.png/ff4444/ffffff', 'Stay hydrated with refreshing flavored water.');
insert into product_images (product_id, url, alt_text) values (20, 'http://dummyimage.com/178x162.png/5fa2dd/ffffff', 'Easy-to-heat frozen burritos for a quick meal.');
insert into product_images (product_id, url, alt_text) values (21, 'http://dummyimage.com/154x160.png/ff4444/ffffff', 'Eco-friendly bags for picking up after your pet.');
insert into product_images (product_id, url, alt_text) values (22, 'http://dummyimage.com/214x165.png/ff4444/ffffff', 'Tender carrots glazed with a sweet maple sauce.');
insert into product_images (product_id, url, alt_text) values (23, 'http://dummyimage.com/151x187.png/cc0000/ffffff', 'Sweet, chewy dried apricots, great for snacking or baking.');
insert into product_images (product_id, url, alt_text) values (24, 'http://dummyimage.com/245x142.png/dddddd/000000', 'Comfortable wireless headphones designed for sleeping.');
insert into product_images (product_id, url, alt_text) values (25, 'http://dummyimage.com/242x226.png/5fa2dd/ffffff', 'Stylish tote to keep wine bottles chilled while traveling.');
insert into product_images (product_id, url, alt_text) values (26, 'http://dummyimage.com/120x173.png/ff4444/ffffff', 'Crispy chips made from assorted garden vegetables, lightly salted.');
insert into product_images (product_id, url, alt_text) values (27, 'http://dummyimage.com/117x236.png/ff4444/ffffff', 'A hearty salad with lentils, veggies, and curry dressing.');
insert into product_images (product_id, url, alt_text) values (28, 'http://dummyimage.com/190x134.png/cc0000/ffffff', 'Creamy honey mustard sauce for dipping or dressing.');
insert into product_images (product_id, url, alt_text) values (29, 'http://dummyimage.com/155x110.png/dddddd/000000', 'Complete outdoor kit for camping and hiking.');
insert into product_images (product_id, url, alt_text) values (30, 'http://dummyimage.com/177x184.png/5fa2dd/ffffff', 'Frozen vegetable primavera for quick meals.');
insert into product_images (product_id, url, alt_text) values (31, 'http://dummyimage.com/177x192.png/cc0000/ffffff', 'Sweet and salty kettle corn, perfect for snacking.');
insert into product_images (product_id, url, alt_text) values (32, 'http://dummyimage.com/152x123.png/5fa2dd/ffffff', 'Water-resistant blanket for picnics and outdoor events.');
insert into product_images (product_id, url, alt_text) values (33, 'http://dummyimage.com/105x217.png/5fa2dd/ffffff', 'Stylish tote to keep wine bottles chilled while traveling.');
insert into product_images (product_id, url, alt_text) values (34, 'http://dummyimage.com/219x240.png/5fa2dd/ffffff', 'Creamy peanut butter with no added sugar or oils.');
insert into product_images (product_id, url, alt_text) values (35, 'http://dummyimage.com/177x168.png/ff4444/ffffff', 'Quick boiling kettle for small kitchens and dorms.');
insert into product_images (product_id, url, alt_text) values (36, 'http://dummyimage.com/130x188.png/5fa2dd/ffffff', 'Energy-efficient LED bulbs that can be controlled via smartphone.');
insert into product_images (product_id, url, alt_text) values (37, 'http://dummyimage.com/136x158.png/5fa2dd/ffffff', 'Concentrated tomato paste, great for sauces.');
insert into product_images (product_id, url, alt_text) values (38, 'http://dummyimage.com/120x152.png/ff4444/ffffff', 'Natural honey sourced from wildflowers.');
insert into product_images (product_id, url, alt_text) values (39, 'http://dummyimage.com/123x243.png/ff4444/ffffff', 'Comfortable camping mattress that inflates automatically.');
insert into product_images (product_id, url, alt_text) values (40, 'http://dummyimage.com/238x125.png/ff4444/ffffff', 'Variety of bands suitable for all fitness levels.');
insert into product_images (product_id, url, alt_text) values (41, 'http://dummyimage.com/250x140.png/dddddd/000000', 'A nourishing bowl of sweet potatoes and chickpeas with spices.');
insert into product_images (product_id, url, alt_text) values (42, 'http://dummyimage.com/186x158.png/ff4444/ffffff', 'Borosilicate glass water bottle with silicone sleeve.');
insert into product_images (product_id, url, alt_text) values (43, 'http://dummyimage.com/104x144.png/5fa2dd/ffffff', 'Wild-caught tuna in olive oil, perfect for salads.');
insert into product_images (product_id, url, alt_text) values (44, 'http://dummyimage.com/138x217.png/5fa2dd/ffffff', 'A sweet and spicy sauce for dipping or glazing.');
insert into product_images (product_id, url, alt_text) values (45, 'http://dummyimage.com/161x221.png/cc0000/ffffff', 'Cold-pressed coconut oil, perfect for cooking, baking, or skin care.');
insert into product_images (product_id, url, alt_text) values (46, 'http://dummyimage.com/198x189.png/cc0000/ffffff', 'A spice blend for making flavorful chili con carne.');
insert into product_images (product_id, url, alt_text) values (47, 'http://dummyimage.com/122x120.png/dddddd/000000', 'Frozen green peas, a great addition to meals.');
insert into product_images (product_id, url, alt_text) values (48, 'http://dummyimage.com/179x101.png/ff4444/ffffff', 'Crispy mini pretzels, a great snack any time of day.');
insert into product_images (product_id, url, alt_text) values (49, 'http://dummyimage.com/133x224.png/5fa2dd/ffffff', 'Refreshing tea with honey and lemon flavor, perfect for a warm drink.');
insert into product_images (product_id, url, alt_text) values (50, 'http://dummyimage.com/166x205.png/cc0000/ffffff', 'Fresh mango salsa with a hint of lime for a zesty topping.');

-- Seed bids

insert into bids (price, automated, product_id, user_id) values (692.07, true, 1, 2);
insert into bids (price, automated, product_id, user_id) values (830.91, true, 2, 1);
insert into bids (price, automated, product_id, user_id) values (220.43, true, 3, 2);
insert into bids (price, automated, product_id, user_id) values (115.33, false, 4, 1);
insert into bids (price, automated, product_id, user_id) values (709.35, false, 5, 2);
insert into bids (price, automated, product_id, user_id) values (576.96, false, 6, 2);
insert into bids (price, automated, product_id, user_id) values (302.78, false, 7, 1);
insert into bids (price, automated, product_id, user_id) values (497.89, true, 8, 4);
insert into bids (price, automated, product_id, user_id) values (472.92, true, 9, 3);
insert into bids (price, automated, product_id, user_id) values (840.9, false, 10, 2);
insert into bids (price, automated, product_id, user_id) values (561.91, false, 11, 3);
insert into bids (price, automated, product_id, user_id) values (518.88, true, 12, 3);
insert into bids (price, automated, product_id, user_id) values (504.41, true, 13, 1);
insert into bids (price, automated, product_id, user_id) values (200.82, true, 14, 1);
insert into bids (price, automated, product_id, user_id) values (736.62, true, 15, 1);
insert into bids (price, automated, product_id, user_id) values (565.31, false, 16, 4);
insert into bids (price, automated, product_id, user_id) values (725.4, false, 17, 4);
insert into bids (price, automated, product_id, user_id) values (725.81, false, 18, 2);
insert into bids (price, automated, product_id, user_id) values (113.98, false, 19, 2);
insert into bids (price, automated, product_id, user_id) values (785.19, true, 20, 3);
insert into bids (price, automated, product_id, user_id) values (400.7, false, 21, 2);
insert into bids (price, automated, product_id, user_id) values (474.23, true, 22, 3);
insert into bids (price, automated, product_id, user_id) values (888.67, false, 23, 3);
insert into bids (price, automated, product_id, user_id) values (817.02, true, 24, 3);
insert into bids (price, automated, product_id, user_id) values (839.08, true, 25, 4);
insert into bids (price, automated, product_id, user_id) values (564.81, true, 26, 3);
insert into bids (price, automated, product_id, user_id) values (453.19, true, 27, 2);
insert into bids (price, automated, product_id, user_id) values (961.42, true, 28, 2);
insert into bids (price, automated, product_id, user_id) values (505.39, true, 29, 1);
insert into bids (price, automated, product_id, user_id) values (443.98, false, 30, 4);
insert into bids (price, automated, product_id, user_id) values (252.6, false, 31, 3);
insert into bids (price, automated, product_id, user_id) values (263.34, true, 32, 2);
insert into bids (price, automated, product_id, user_id) values (168.05, true, 33, 1);
insert into bids (price, automated, product_id, user_id) values (154.04, false, 34, 4);
insert into bids (price, automated, product_id, user_id) values (525.34, true, 35, 2);
insert into bids (price, automated, product_id, user_id) values (549.21, true, 36, 4);
insert into bids (price, automated, product_id, user_id) values (478.02, false, 37, 1);
insert into bids (price, automated, product_id, user_id) values (538.22, true, 38, 4);
insert into bids (price, automated, product_id, user_id) values (307.97, false, 39, 4);
insert into bids (price, automated, product_id, user_id) values (975.34, false, 40, 1);
insert into bids (price, automated, product_id, user_id) values (700.68, false, 41, 1);
insert into bids (price, automated, product_id, user_id) values (891.92, false, 42, 3);
insert into bids (price, automated, product_id, user_id) values (607.79, true, 43, 4);
insert into bids (price, automated, product_id, user_id) values (397.29, false, 44, 3);
insert into bids (price, automated, product_id, user_id) values (248.37, true, 45, 3);
insert into bids (price, automated, product_id, user_id) values (837.64, true, 46, 2);
insert into bids (price, automated, product_id, user_id) values (446.32, true, 47, 3);
insert into bids (price, automated, product_id, user_id) values (705.9, true, 48, 3);
insert into bids (price, automated, product_id, user_id) values (902.17, false, 49, 3);
insert into bids (price, automated, product_id, user_id) values (751.59, true, 50, 2);
insert into bids (price, automated, product_id, user_id) values (208.96, true, 1, 3);
insert into bids (price, automated, product_id, user_id) values (683.96, false, 2, 4);
insert into bids (price, automated, product_id, user_id) values (943.78, false, 3, 1);
insert into bids (price, automated, product_id, user_id) values (76.9, true, 4, 4);
insert into bids (price, automated, product_id, user_id) values (665.77, false, 5, 3);
insert into bids (price, automated, product_id, user_id) values (336.24, true, 6, 4);
insert into bids (price, automated, product_id, user_id) values (97.96, true, 7, 4);
insert into bids (price, automated, product_id, user_id) values (297.96, false, 8, 2);
insert into bids (price, automated, product_id, user_id) values (74.77, false, 9, 1);
insert into bids (price, automated, product_id, user_id) values (537.25, true, 10, 2);
insert into bids (price, automated, product_id, user_id) values (257.88, true, 11, 3);
insert into bids (price, automated, product_id, user_id) values (152.51, true, 12, 3);
insert into bids (price, automated, product_id, user_id) values (293.77, true, 13, 3);
insert into bids (price, automated, product_id, user_id) values (190.09, true, 14, 3);
insert into bids (price, automated, product_id, user_id) values (952.92, false, 15, 4);
insert into bids (price, automated, product_id, user_id) values (97.81, false, 16, 1);
insert into bids (price, automated, product_id, user_id) values (800.75, false, 17, 2);
insert into bids (price, automated, product_id, user_id) values (436.6, true, 18, 4);
insert into bids (price, automated, product_id, user_id) values (701.92, false, 19, 2);
insert into bids (price, automated, product_id, user_id) values (715.96, true, 20, 2);
insert into bids (price, automated, product_id, user_id) values (918.44, true, 21, 2);
insert into bids (price, automated, product_id, user_id) values (924.29, true, 22, 1);
insert into bids (price, automated, product_id, user_id) values (327.08, false, 23, 1);
insert into bids (price, automated, product_id, user_id) values (795.1, true, 24, 1);
insert into bids (price, automated, product_id, user_id) values (854.34, false, 25, 2);
insert into bids (price, automated, product_id, user_id) values (268.73, true, 26, 2);
insert into bids (price, automated, product_id, user_id) values (521.4, false, 27, 3);
insert into bids (price, automated, product_id, user_id) values (553.9, true, 28, 2);
insert into bids (price, automated, product_id, user_id) values (163.86, false, 29, 3);
insert into bids (price, automated, product_id, user_id) values (675.35, true, 30, 4);
insert into bids (price, automated, product_id, user_id) values (623.33, false, 31, 4);
insert into bids (price, automated, product_id, user_id) values (163.71, false, 32, 2);
insert into bids (price, automated, product_id, user_id) values (72.54, true, 33, 4);
insert into bids (price, automated, product_id, user_id) values (970.23, false, 34, 2);
insert into bids (price, automated, product_id, user_id) values (568.89, true, 35, 4);
insert into bids (price, automated, product_id, user_id) values (348.59, false, 36, 3);
insert into bids (price, automated, product_id, user_id) values (369.63, false, 37, 1);
insert into bids (price, automated, product_id, user_id) values (672.69, true, 38, 4);
insert into bids (price, automated, product_id, user_id) values (728.7, false, 39, 4);
insert into bids (price, automated, product_id, user_id) values (277.06, true, 40, 2);
insert into bids (price, automated, product_id, user_id) values (542.55, true, 41, 4);
insert into bids (price, automated, product_id, user_id) values (128.93, true, 42, 3);
insert into bids (price, automated, product_id, user_id) values (929.09, true, 43, 2);
insert into bids (price, automated, product_id, user_id) values (372.78, false, 44, 3);
insert into bids (price, automated, product_id, user_id) values (689.01, true, 45, 1);
insert into bids (price, automated, product_id, user_id) values (126.47, false, 46, 1);
insert into bids (price, automated, product_id, user_id) values (227.31, false, 47, 3);
insert into bids (price, automated, product_id, user_id) values (626.05, false, 48, 1);
insert into bids (price, automated, product_id, user_id) values (432.09, false, 49, 3);
insert into bids (price, automated, product_id, user_id) values (196.64, true, 50, 3);
insert into bids (price, automated, product_id, user_id) values (936.34, false, 1, 3);
insert into bids (price, automated, product_id, user_id) values (534.01, true, 2, 4);
insert into bids (price, automated, product_id, user_id) values (165.21, false, 3, 1);
insert into bids (price, automated, product_id, user_id) values (327.63, false, 4, 1);
insert into bids (price, automated, product_id, user_id) values (801.88, true, 5, 4);
insert into bids (price, automated, product_id, user_id) values (805.0, true, 6, 2);
insert into bids (price, automated, product_id, user_id) values (460.79, true, 7, 1);
insert into bids (price, automated, product_id, user_id) values (699.52, false, 8, 2);
insert into bids (price, automated, product_id, user_id) values (482.47, true, 9, 3);
insert into bids (price, automated, product_id, user_id) values (920.87, false, 10, 1);
insert into bids (price, automated, product_id, user_id) values (819.23, false, 11, 4);
insert into bids (price, automated, product_id, user_id) values (251.82, false, 12, 1);
insert into bids (price, automated, product_id, user_id) values (236.13, false, 13, 3);
insert into bids (price, automated, product_id, user_id) values (671.77, false, 14, 4);
insert into bids (price, automated, product_id, user_id) values (727.49, false, 15, 4);
insert into bids (price, automated, product_id, user_id) values (746.35, false, 16, 2);
insert into bids (price, automated, product_id, user_id) values (137.84, false, 17, 3);
insert into bids (price, automated, product_id, user_id) values (459.23, true, 18, 4);
insert into bids (price, automated, product_id, user_id) values (830.18, false, 19, 3);
insert into bids (price, automated, product_id, user_id) values (277.31, false, 20, 1);
insert into bids (price, automated, product_id, user_id) values (161.07, false, 21, 1);
insert into bids (price, automated, product_id, user_id) values (336.0, false, 22, 2);
insert into bids (price, automated, product_id, user_id) values (691.06, true, 23, 3);
insert into bids (price, automated, product_id, user_id) values (515.98, true, 24, 2);
insert into bids (price, automated, product_id, user_id) values (520.6, false, 25, 1);
insert into bids (price, automated, product_id, user_id) values (861.01, false, 26, 3);
insert into bids (price, automated, product_id, user_id) values (788.85, true, 27, 3);
insert into bids (price, automated, product_id, user_id) values (245.73, true, 28, 3);
insert into bids (price, automated, product_id, user_id) values (767.82, true, 29, 1);
insert into bids (price, automated, product_id, user_id) values (602.19, true, 30, 2);
insert into bids (price, automated, product_id, user_id) values (85.85, true, 31, 1);
insert into bids (price, automated, product_id, user_id) values (729.12, true, 32, 2);
insert into bids (price, automated, product_id, user_id) values (681.55, false, 33, 3);
insert into bids (price, automated, product_id, user_id) values (166.63, false, 34, 4);
insert into bids (price, automated, product_id, user_id) values (212.25, false, 35, 1);
insert into bids (price, automated, product_id, user_id) values (218.6, true, 36, 4);
insert into bids (price, automated, product_id, user_id) values (24.88, true, 37, 1);
insert into bids (price, automated, product_id, user_id) values (660.02, false, 38, 2);
insert into bids (price, automated, product_id, user_id) values (734.97, false, 39, 1);
insert into bids (price, automated, product_id, user_id) values (91.27, false, 40, 3);
insert into bids (price, automated, product_id, user_id) values (422.68, true, 41, 2);
insert into bids (price, automated, product_id, user_id) values (917.95, true, 42, 4);
insert into bids (price, automated, product_id, user_id) values (448.72, true, 43, 1);
insert into bids (price, automated, product_id, user_id) values (156.75, true, 44, 3);
insert into bids (price, automated, product_id, user_id) values (169.45, true, 45, 3);
insert into bids (price, automated, product_id, user_id) values (181.79, true, 46, 3);
insert into bids (price, automated, product_id, user_id) values (522.58, false, 47, 3);
insert into bids (price, automated, product_id, user_id) values (387.87, true, 48, 3);
insert into bids (price, automated, product_id, user_id) values (974.68, false, 49, 2);
insert into bids (price, automated, product_id, user_id) values (402.19, true, 50, 4);

update products p set bids_count = (select count(1) from bids where product_id = p.id);
update products p set current_highest_bid_id = (select id from bids where product_id = p.id order by price desc limit 1);

-- Seed questions

insert into questions (content, answer, product_id, user_id) values ('Seamless scalable flexibility', null, 1, 4);
insert into questions (content, answer, product_id, user_id) values ('Up-sized optimizing circuit', 'Enterprise-wide bifurcated framework', 2, 4);
insert into questions (content, answer, product_id, user_id) values ('Exclusive contextually-based implementation', 'Future-proofed dynamic time-frame', 3, 3);
insert into questions (content, answer, product_id, user_id) values ('De-engineered attitude-oriented paradigm', null, 4, 4);
insert into questions (content, answer, product_id, user_id) values ('Streamlined client-server capability', null, 5, 1);
insert into questions (content, answer, product_id, user_id) values ('Managed modular success', 'Balanced 4th generation knowledge base', 6, 3);
insert into questions (content, answer, product_id, user_id) values ('Multi-lateral zero defect time-frame', 'Profound 5th generation productivity', 7, 1);
insert into questions (content, answer, product_id, user_id) values ('Triple-buffered explicit parallelism', 'Advanced bottom-line success', 8, 4);
insert into questions (content, answer, product_id, user_id) values ('Configurable incremental time-frame', 'Profound radical orchestration', 9, 4);
insert into questions (content, answer, product_id, user_id) values ('Exclusive solution-oriented open system', null, 10, 1);
insert into questions (content, answer, product_id, user_id) values ('Managed real-time alliance', 'Synergistic neutral moderator', 11, 4);
insert into questions (content, answer, product_id, user_id) values ('Grass-roots clear-thinking collaboration', null, 12, 2);
insert into questions (content, answer, product_id, user_id) values ('Managed empowering knowledge base', null, 13, 3);
insert into questions (content, answer, product_id, user_id) values ('Multi-channelled multi-tasking parallelism', null, 14, 2);
insert into questions (content, answer, product_id, user_id) values ('Monitored eco-centric infrastructure', 'Seamless radical workforce', 15, 2);
insert into questions (content, answer, product_id, user_id) values ('Compatible national monitoring', null, 16, 4);
insert into questions (content, answer, product_id, user_id) values ('Grass-roots clear-thinking challenge', null, 17, 2);
insert into questions (content, answer, product_id, user_id) values ('Digitized explicit functionalities', 'Synchronised encompassing projection', 18, 1);
insert into questions (content, answer, product_id, user_id) values ('Cross-platform uniform array', null, 19, 4);
insert into questions (content, answer, product_id, user_id) values ('Re-contextualized user-facing implementation', null, 20, 3);
insert into questions (content, answer, product_id, user_id) values ('Customizable system-worthy info-mediaries', 'Horizontal needs-based collaboration', 21, 1);
insert into questions (content, answer, product_id, user_id) values ('Right-sized impactful standardization', 'Inverse stable monitoring', 22, 1);
insert into questions (content, answer, product_id, user_id) values ('Optimized multimedia customer loyalty', 'Open-source homogeneous access', 23, 1);
insert into questions (content, answer, product_id, user_id) values ('Future-proofed fresh-thinking open system', null, 24, 3);
insert into questions (content, answer, product_id, user_id) values ('Innovative web-enabled open system', 'Innovative uniform info-mediaries', 25, 2);
insert into questions (content, answer, product_id, user_id) values ('Profit-focused uniform analyzer', 'Re-engineered bottom-line array', 26, 3);
insert into questions (content, answer, product_id, user_id) values ('Multi-tiered impactful throughput', null, 27, 4);
insert into questions (content, answer, product_id, user_id) values ('Persistent exuding customer loyalty', 'Realigned responsive matrices', 28, 4);
insert into questions (content, answer, product_id, user_id) values ('Versatile optimal success', 'Automated systemic moderator', 29, 4);
insert into questions (content, answer, product_id, user_id) values ('Centralized neutral functionalities', null, 30, 3);
insert into questions (content, answer, product_id, user_id) values ('Switchable real-time groupware', 'Streamlined mobile website', 31, 2);
insert into questions (content, answer, product_id, user_id) values ('Programmable optimal access', 'Grass-roots transitional access', 32, 4);
insert into questions (content, answer, product_id, user_id) values ('Fully-configurable composite framework', 'Optimized multimedia instruction set', 33, 1);
insert into questions (content, answer, product_id, user_id) values ('Horizontal scalable knowledge base', 'Adaptive bifurcated access', 34, 3);
insert into questions (content, answer, product_id, user_id) values ('De-engineered 3rd generation functionalities', 'Centralized web-enabled structure', 35, 1);
insert into questions (content, answer, product_id, user_id) values ('De-engineered actuating ability', 'Intuitive neutral moderator', 36, 4);
insert into questions (content, answer, product_id, user_id) values ('User-centric human-resource installation', 'Function-based interactive array', 37, 1);
insert into questions (content, answer, product_id, user_id) values ('Monitored system-worthy implementation', null, 38, 3);
insert into questions (content, answer, product_id, user_id) values ('Vision-oriented 5th generation policy', 'Upgradable asynchronous orchestration', 39, 1);
insert into questions (content, answer, product_id, user_id) values ('Phased solution-oriented internet solution', 'Open-source content-based challenge', 40, 2);
insert into questions (content, answer, product_id, user_id) values ('Programmable impactful workforce', null, 41, 2);
insert into questions (content, answer, product_id, user_id) values ('Diverse intangible process improvement', null, 42, 2);
insert into questions (content, answer, product_id, user_id) values ('Expanded attitude-oriented interface', 'Advanced fresh-thinking website', 43, 2);
insert into questions (content, answer, product_id, user_id) values ('Seamless maximized attitude', 'Fundamental uniform success', 44, 4);
insert into questions (content, answer, product_id, user_id) values ('Centralized zero tolerance concept', 'Networked static open architecture', 45, 3);
insert into questions (content, answer, product_id, user_id) values ('Synergistic zero tolerance capability', 'Universal explicit parallelism', 46, 1);
insert into questions (content, answer, product_id, user_id) values ('Visionary homogeneous interface', null, 47, 2);
insert into questions (content, answer, product_id, user_id) values ('Right-sized logistical benchmark', 'Fully-configurable static hub', 48, 3);
insert into questions (content, answer, product_id, user_id) values ('Profound local portal', null, 49, 3);
insert into questions (content, answer, product_id, user_id) values ('Secured system-worthy flexibility', null, 50, 3);
insert into questions (content, answer, product_id, user_id) values ('Multi-layered background throughput', 'Reduced intermediate model', 1, 4);
insert into questions (content, answer, product_id, user_id) values ('Multi-tiered encompassing software', 'Balanced stable website', 2, 2);
insert into questions (content, answer, product_id, user_id) values ('Networked content-based pricing structure', null, 3, 4);
insert into questions (content, answer, product_id, user_id) values ('Visionary logistical monitoring', null, 4, 1);
insert into questions (content, answer, product_id, user_id) values ('Down-sized asymmetric protocol', null, 5, 1);
insert into questions (content, answer, product_id, user_id) values ('Cloned 3rd generation utilisation', 'Cross-group client-driven model', 6, 2);
insert into questions (content, answer, product_id, user_id) values ('Networked upward-trending toolset', 'Advanced discrete capacity', 7, 4);
insert into questions (content, answer, product_id, user_id) values ('Cross-group reciprocal productivity', 'Multi-channelled holistic capability', 8, 2);
insert into questions (content, answer, product_id, user_id) values ('Synergistic value-added project', 'Streamlined motivating policy', 9, 1);
insert into questions (content, answer, product_id, user_id) values ('Ergonomic tangible hierarchy', 'Synergistic value-added hierarchy', 10, 3);
insert into questions (content, answer, product_id, user_id) values ('Front-line bandwidth-monitored website', 'Self-enabling multimedia artificial intelligence', 11, 2);
insert into questions (content, answer, product_id, user_id) values ('Networked analyzing extranet', 'Progressive dedicated help-desk', 12, 1);
insert into questions (content, answer, product_id, user_id) values ('Diverse context-sensitive policy', 'Business-focused optimizing matrix', 13, 2);
insert into questions (content, answer, product_id, user_id) values ('Programmable contextually-based contingency', 'Advanced asymmetric artificial intelligence', 14, 1);
insert into questions (content, answer, product_id, user_id) values ('Ergonomic maximized open system', 'Multi-lateral clear-thinking forecast', 15, 3);
insert into questions (content, answer, product_id, user_id) values ('Mandatory radical intranet', 'Multi-tiered multi-tasking project', 16, 2);
insert into questions (content, answer, product_id, user_id) values ('Quality-focused logistical collaboration', 'Compatible methodical concept', 17, 1);
insert into questions (content, answer, product_id, user_id) values ('Persistent asynchronous pricing structure', 'Stand-alone needs-based support', 18, 2);
insert into questions (content, answer, product_id, user_id) values ('Realigned zero tolerance application', 'Reactive 3rd generation data-warehouse', 19, 3);
insert into questions (content, answer, product_id, user_id) values ('User-centric interactive collaboration', 'Digitized multi-tasking interface', 20, 3);
insert into questions (content, answer, product_id, user_id) values ('Mandatory local system engine', 'Inverse maximized process improvement', 21, 4);
insert into questions (content, answer, product_id, user_id) values ('Managed bottom-line product', 'Cloned local moratorium', 22, 3);
insert into questions (content, answer, product_id, user_id) values ('Programmable static hardware', 'Fundamental exuding system engine', 23, 4);
insert into questions (content, answer, product_id, user_id) values ('Automated directional time-frame', 'Virtual clear-thinking focus group', 24, 1);
insert into questions (content, answer, product_id, user_id) values ('Vision-oriented modular firmware', 'Ergonomic foreground functionalities', 25, 3);
insert into questions (content, answer, product_id, user_id) values ('Operative interactive attitude', 'Front-line disintermediate service-desk', 26, 2);
insert into questions (content, answer, product_id, user_id) values ('Reactive responsive productivity', 'Focused hybrid internet solution', 27, 2);
insert into questions (content, answer, product_id, user_id) values ('Secured radical conglomeration', 'Enterprise-wide didactic complexity', 28, 1);
insert into questions (content, answer, product_id, user_id) values ('De-engineered systematic migration', 'Synchronised exuding orchestration', 29, 4);
insert into questions (content, answer, product_id, user_id) values ('Cross-group static toolset', 'Devolved tangible info-mediaries', 30, 2);
insert into questions (content, answer, product_id, user_id) values ('Decentralized bottom-line frame', 'Expanded disintermediate portal', 31, 1);
insert into questions (content, answer, product_id, user_id) values ('Decentralized asymmetric emulation', 'Robust national forecast', 32, 1);
insert into questions (content, answer, product_id, user_id) values ('Profit-focused client-driven focus group', null, 33, 1);
insert into questions (content, answer, product_id, user_id) values ('Mandatory bottom-line emulation', null, 34, 1);
insert into questions (content, answer, product_id, user_id) values ('Multi-tiered interactive algorithm', 'Assimilated interactive migration', 35, 4);
insert into questions (content, answer, product_id, user_id) values ('Persevering interactive concept', null, 36, 1);
insert into questions (content, answer, product_id, user_id) values ('Quality-focused intangible open system', 'Ameliorated multimedia conglomeration', 37, 1);
insert into questions (content, answer, product_id, user_id) values ('Inverse mobile model', 'Implemented modular access', 38, 1);
insert into questions (content, answer, product_id, user_id) values ('Open-source well-modulated utilisation', null, 39, 2);
insert into questions (content, answer, product_id, user_id) values ('Distributed hybrid circuit', null, 40, 2);
insert into questions (content, answer, product_id, user_id) values ('Triple-buffered 24/7 support', 'Cross-platform interactive array', 41, 1);
insert into questions (content, answer, product_id, user_id) values ('Configurable logistical synergy', 'Implemented cohesive methodology', 42, 3);
insert into questions (content, answer, product_id, user_id) values ('Stand-alone fresh-thinking adapter', 'Seamless holistic support', 43, 2);
insert into questions (content, answer, product_id, user_id) values ('Profound radical adapter', 'Re-engineered interactive collaboration', 44, 3);
insert into questions (content, answer, product_id, user_id) values ('Horizontal methodical matrices', null, 45, 3);
insert into questions (content, answer, product_id, user_id) values ('Public-key optimizing framework', 'Ergonomic well-modulated capacity', 46, 4);
insert into questions (content, answer, product_id, user_id) values ('Expanded leading edge implementation', 'Object-based 6th generation time-frame', 47, 3);
insert into questions (content, answer, product_id, user_id) values ('Automated content-based installation', 'Customizable 3rd generation internet solution', 48, 1);
insert into questions (content, answer, product_id, user_id) values ('Synchronised logistical hierarchy', 'Reverse-engineered tangible toolset', 49, 2);
insert into questions (content, answer, product_id, user_id) values ('User-friendly well-modulated model', 'Expanded next generation support', 50, 2);
